name: Build CV PDF

on:
  push:
    # only rebuild when you change .tex/.bib files
    paths:
      - '**.tex'
      - '**.bib'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v3
        with:
          # so we can push back
          persist-credentials: true

      - name: Install LaTeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk biber

      - name: Set up TeX Live
        uses: teatimeguest/setup-texlive-action@v3.4.1

      - name: Build PDF
        run: |
          # Verify latexmk is installed
          which latexmk
          # Build the PDF from your main .tex file
          latexmk -pdf RegisKopperCV.tex
          # Rename output to cv.pdf for consistency
          mv RegisKopperCV.pdf cv.pdf

      - name: Debug workspace
        run: |
          echo "Workspace contents after build:"
          ls -lh .

      - name: Commit & push PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f cv.pdf
          # only commit (and push) if it changed
          git diff --quiet --exit-code || \
            (git commit -m "chore: rebuild CV PDF [skip ci]" && git push)
